import 'recentorders_item_model.dart';import '../../../core/app_export.dart';import 'doctorreviews_item_model.dart';import 'itemlist_item_model.dart';import 'userprofile_item_model.dart';import 'topproducts_item_model.dart';import 'dresses_item_model.dart';import 'justforyou_item_model.dart';/// This class defines the variables used in the [full_profile_page],
/// and is typically used to hold data that is passed between different parts of the application.
class FullProfileModel {Rx<List<RecentordersItemModel>> recentordersItemList = Rx(List.generate(9,(index) => RecentordersItemModel()));

Rx<List<DoctorreviewsItemModel>> doctorreviewsItemList = Rx([DoctorreviewsItemModel(liveImage:ImageConstant.imgBfc6a77aC42f4.obs,userImage:ImageConstant.imgUserOnerrorcontainer.obs),DoctorreviewsItemModel(liveImage:ImageConstant.img0e33d0844dab4175x104.obs,userImage:ImageConstant.imgUserOnerrorcontainer.obs),DoctorreviewsItemModel(liveImage:ImageConstant.img9bf6accf20464.obs,userImage:ImageConstant.imgUserOnerrorcontainer.obs),DoctorreviewsItemModel(liveImage:ImageConstant.img14d5128d5fff4.obs,userImage:ImageConstant.imgUserOnerrorcontainer.obs)]);

Rx<List<ItemlistItemModel>> itemlistItemList = Rx([ItemlistItemModel(image1:ImageConstant.imgC68139e1363c4.obs,image2:ImageConstant.img45d808e05e004.obs,text1: "Lorem ipsum dolor sit amet consectetur.".obs,text2: "17,00".obs),ItemlistItemModel(text1: "Lorem ipsum dolor sit amet consectetur.".obs,text2: "32,00".obs),ItemlistItemModel(text1: "Lorem ipsum dolor sit amet consectetur.".obs,text2: "21,00".obs)]);

Rx<List<UserprofileItemModel>> userprofileItemList = Rx([UserprofileItemModel(userImage1:ImageConstant.img532c6dcf29ca4.obs,userImage2:ImageConstant.img74c5b250Bcb74.obs,clothing:ImageConstant.img0f26e045Aa024.obs,title: "Clothing".obs,image:ImageConstant.imgA82f288184144.obs,widget: "109".obs),UserprofileItemModel(userImage1:ImageConstant.imgA70864c81b1f4.obs,userImage2:ImageConstant.imgDdf8e2ef1a434.obs,clothing:ImageConstant.img6d305338A2a14.obs,title: "Shoes".obs,image:ImageConstant.imgA0a54f52A5f34.obs,widget: "530".obs),UserprofileItemModel(userImage1:ImageConstant.img1f888cabA0654.obs,userImage2:ImageConstant.img3f402e7a16744.obs,clothing:ImageConstant.img83ad853c1a814.obs,title: "Bags".obs,image:ImageConstant.img27ce7b248b284.obs,widget: "87".obs),UserprofileItemModel(userImage1:ImageConstant.imgF2e8e4c3E5f74.obs,userImage2:ImageConstant.img18e41c341da04.obs,clothing:ImageConstant.imgF8382341Af5b4.obs,title: "Lingerie".obs,image:ImageConstant.imgB35cfc93A1b94.obs,widget: "218".obs)]);

Rx<List<TopproductsItemModel>> topproductsItemList = Rx([TopproductsItemModel(userImage:ImageConstant.img2289c231211f4103x99.obs,titleText: "-20%".obs),TopproductsItemModel(userImage:ImageConstant.img88cab39f41684.obs,titleText: "-20%".obs),TopproductsItemModel(userImage:ImageConstant.img84439dcd10ef4.obs,titleText: "-20%".obs),TopproductsItemModel(titleText: "-20%".obs),TopproductsItemModel(titleText: "-20%".obs),TopproductsItemModel(titleText: "-20%".obs)]);

Rx<List<DressesItemModel>> dressesItemList = Rx(List.generate(5,(index) => DressesItemModel()));

Rx<List<JustforyouItemModel>> justforyouItemList = Rx([JustforyouItemModel(image:ImageConstant.img45d808e05e004171x155.obs,text1: "Lorem ipsum dolor sit amet consectetur".obs,text2: "17,00".obs),JustforyouItemModel(image:ImageConstant.img50c51a0fBc204.obs,text1: "Lorem ipsum dolor sit amet consectetur".obs,text2: "17,00".obs),JustforyouItemModel(text1: "Lorem ipsum dolor sit amet consectetur".obs,text2: "17,00".obs),JustforyouItemModel(text1: "Lorem ipsum dolor sit amet consectetur".obs,text2: "17,00".obs)]);

 }
